spring.application.name=Config-Service
spring.cloud.config.server.git.uri=https://github.com/SohamBhandary/lovable-config-server
spring.cloud.config.server.git.username=SohamBhandary
# Use your GitHub PAT as the password
spring.cloud.config.server.git.password=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
spring.cloud.config.server.git.default-label=main
server.port=8888