spring.application.name=Workspace-Service
spring.cloud.config.fail-fast=true

# If you are using Spring Boot 3+, use this syntax to point to your config server:
spring.config.import=optional:configserver:http://localhost:8888