# ===========================
# Main PostgreSQL Database
# ===========================
spring.datasource.url=jdbc:postgresql://localhost:5432/lovable
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ===========================
# PGVector Database
# ===========================
pgvector.datasource.url=jdbc:postgresql://localhost:9010/pgvector-test
pgvector.datasource.username=user
pgvector.datasource.password=password
pgvector.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false

# ===========================
# Environment
# ===========================
spring.config.import=optional:file:.env[.properties]

jwt.secret-key=${SECRET}

stripe.secret=${stripe.secret}
client.url=${client.url}
stripe.webhookSecret=${stripe.webhookSecret}

# ===========================
# OpenAI
# ===========================
spring.ai.openai.base-url=https://api.aicredits.in
spring.ai.openai.api-key=${AICREDITS_API_KEY}

spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.7


# Logging
logging.level.org.springframework.ai=INFO
logging.level.org.springframework.ai.chat.client=DEBUG

# MinIO
minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.project-bucket=projects